module.exports = {
  apps: [
    {
      name: "front",
      script: "docker",
      args: [
        "run",
        "-d",
        "--rm",
        "--name",
        "aicity-front",
        "-p",
        "3000:3000",
        "-e",
        "NEXT_PUBLIC_API_URL=http://localhost:3001/api",
        "-e",
        "NEXT_PUBLIC_WS_URL=ws://localhost:3002",
        "aicity-front",
      ],
      autorestart: true,
    },
    {
      name: "back",
      script: "docker",
      args: [
        "run",
        "-d",
        "--rm",
        "--name",
        "aicity-backend",
        "-p",
        "3001:3001",
        "-p",
        "3002:3002",
        "-e",
        "CORS_ORIGIN=http://localhost:3000",
        "-e",
        "WS_ORIGIN=http://localhost:3000",
        "aicity-backend",
      ],
      autorestart: true,
    },
    {
      name: "nginx",
      script: "docker",
      args: [
        "run",
        "-d",
        "--rm",
        "--name",
        "aicity-nginx",
        "-p",
        "80:80",
        "-p",
        "443:443",
        "-v",
        "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro",
        "-v",
        "/etc/letsencrypt:/etc/letsencrypt:ro",
        "nginx:alpine",
      ],
      autorestart: true,
    },
  ],
};
