name: Deploy Backend to EC2

on:
  push:
    branches: [master]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'DEPLOY')
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy Backend to EC2
        run: |
          ssh ec2 'cd /home/ec2-user/apps/backend/aicity-backend && \
          git pull origin master && \
          echo "Initial cleanup..." && \
          # First attempt to stop and remove
          docker stop aicity-backend || echo "No container to stop" && \
          docker rm -f aicity-backend || echo "No container to remove" && \
          # Verify removal
          if docker ps -a --format "{{.Names}}" | grep -q "^aicity-backend$"; then \
            echo "Container still exists after first removal attempt" && \
            docker rm -f $(docker ps -a -q --filter name=aicity-backend) || true && \
            sleep 3 \
          fi && \
          # Final verification
          if docker ps -a --format "{{.Names}}" | grep -q "^aicity-backend$"; then \
            echo "Failed to remove container completely" && exit 1 \
          fi && \
          echo "Container cleanup verified" && \
          # Remove old images
          echo "Cleaning up old images..." && \
          docker image prune -f && \
          # Build and run new container
          echo "Building new image..." && \
          docker build -t aicity-backend . && \
          echo "Starting new container..." && \
          # Final check before running
          if docker ps -a --format "{{.Names}}" | grep -q "^aicity-backend$"; then \
            echo "Container still exists before running new one" && \
            docker rm -f $(docker ps -a -q --filter name=aicity-backend) || true && \
            sleep 3 \
          fi && \
          docker run --name aicity-backend --network aicity-network -p 3001:3001 -p 3002:3002 --env-file .env -d aicity-backend'
