name: Deploy Backend to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'DEPLOY')
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy Backend to EC2
        run: |
          ssh ec2 'cd /home/ec2-user/apps/backend/aicity-backend && \
          echo "Pulling latest changes..." && \
          git pull origin main && \
          echo "Checking for running container..." && \
          if docker ps -q -f name=aicity-backend; then \
            echo "Stopping running container..." && \
            docker stop aicity-backend; \
          fi && \
          echo "Removing old container..." && \
          docker rm -f aicity-backend || true && \
          echo "Building new image..." && \
          docker build -t aicity-backend . && \
          echo "Starting new container..." && \
          docker run --name aicity-backend --network aicity-network -p 3001:3001 -p 3002:3002 --env-file .env -d aicity-backend && \
          echo "Verifying deployment..." && \
          sleep 5 && \
          if docker ps | grep aicity-backend; then \
            echo "✅ Deployment successful!"; \
          else \
            echo "❌ Deployment failed!" && exit 1; \
          fi'
